# Generated by Django 4.2 on 2023-04-15 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphenquiry',
            name='html_data',
            field=models.TextField(default=datetime.datetime(2023, 4, 15, 5, 21, 35, 531717, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
