# Generated by Django 4.2 on 2023-04-15 11:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_graphenquiry_html_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphenquiry',
            name='x_axis',
            field=models.CharField(default=datetime.datetime(2023, 4, 15, 11, 53, 33, 907039, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphenquiry',
            name='y_axis',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
