# Generated by Django 4.2 on 2023-04-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_graphenquiry_x_axis_graphenquiry_y_axis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphenquiry',
            name='x_axis',
        ),
        migrations.RemoveField(
            model_name='graphenquiry',
            name='y_axis',
        ),
    ]
